name: your_project_name
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none'

# The following defines the environment:
# sdk: version of the Dart SDK that your package needs.
environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  hive_generator: ^2.0.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # Add build_runner and other code generation dependencies
  build_runner: ^2.0.0
  hive_generator: ^2.0.1  # Ensure this matches the version in dependencies
